### PR TITLE
Cleaning up test.js

### PR DESCRIPTION
**Pull request by fearphage**
Simplified test.js *a little*  based on cjohansen/Sinon.JS#680

### CODE REVIEW

**Comment by fearphage** [comment]
Note: [line 37](686/files#diff-9b1597fcd86fcb2f9919de55d87e6af5R37) overrides the captured result from [line 49](686/files#diff-9b1597fcd86fcb2f9919de55d87e6af5R49). Is that intentional? This was the same way in old code. I think one of them needs to be killed. I couldn't see which one.

**Comment by cjohansen** [comment]
Thanks! I'm not sure either of those has to be killed? This code still has improvement potential :) Thanks for contributing to making it better!

**Comment by fearphage** [comment]
Well there's no reason to store the `result` if it's never used or referenced:

```` javascript
result = callback.apply(this, args.concat(sandbox.args));
````

That's wasted code. I say remove the assignment since no one references it or is able to reference it even.

**Comment by cjohansen** [comment]
That value is later returned: https://github.com/cjohansen/Sinon.JS/blob/32c54084d381293e7452eb982167be9b805933d7/lib/sinon/test.js#L63

**Comment by fearphage** [comment]
Ahhh, I missed that. Thank you.

**Pull request merged**
