### PR TITLE
Spy call: Capture the stack

### PR DESCRIPTION
**Pull request by papandreou**
I tried implementing my suggestion from #747 and added the top stack frame to the `spyCall.toString()` output.

### CODE REVIEW

**Comment by cjohansen** [comment]
This is very cool! Did you test it in multiple browsers? Browsers differ in how they format the stack, would be nice if it worked the same in all of 'em.

**Comment by papandreou** [comment]
You are correct, browsers put different info into the stack traces, and the `stack` property isn't standardized. There are libraries for attempting to normalize and parse the string, and V8 even has a really nice callsite API for avoiding the stringification.

However, introducing something like that would add overhead and could lead to a "lowest common denominator" scenario where actually relevant information would end up being stripped.

In Sinon's case I think the only use case for capturing the stack is to display the non-Sinon stack frames as extra info in `spyCall.toString()`, and I think this PR accomplishes that well enough. But maybe you have other features in mind?

**Comment by cjohansen** [comment]
I guess I was mostly thinking that we should make sure it works the same enough for the tests to pass in all browsers we support. Did you run the tests in multiple browsers?

**Comment by papandreou** [comment]
Tested in:
* Chrome 37.0.2062.120 on Linux
* Opera 12.16 on Linux
* Firefox 26.0 on Linux

Tried hooking additional browsers up to the buster-server setup via browserstack.com, but couldn't get that to work, and not on master either. Got an "All slaves timed out" message.

**Comment by papandreou** [comment]
Thanks :)

**Pull request merged**
