### PR TITLE
Run unit tests against packaged version in CI environment

### PR DESCRIPTION
**Pull request by mroderick**
This PR allows us to run tests against the packaged version in CI environments (or anywhere we care to run the `ci-test.sh` script).

### CODE REVIEW

**Comment by mantoni** [comment]
I love this commit history. It's very entertaining. Although you're most likely banging your head against the wall right now.

**Comment by mroderick** [comment]
> I love this commit history. It's very entertaining. Although you're most likely banging your head against the wall right now.

I am ... but I might be close

**Comment by mroderick** [comment]
@mantoni good to go

**Comment by mantoni** [comment]
Yay! :+1: Looks good to me.

I'm wondering if we should change the dependencies to use at least the `~` prefix instead of being super strict. Especially with `formatio` requiring `samsam` and then `samsam` now being required by Sinon directly as well .... If the versions are not identical, we end up with two versions in the tree.

**Comment by mroderick** [comment]
> I'm wondering if we should change the dependencies to use at least the ~ prefix instead of being super strict. Especially with formatio requiring samsam and then samsam now being required by Sinon directly as well .... If the versions are not identical, we end up with two versions in the tree.

Let's burn that bridge when we get to it

**Comment by cjohansen** [comment]
:+1:

**Pull request merged**
