### PR TITLE
Improve RELEASE.md to reduce effort when cutting a new release

### PR DESCRIPTION
**Pull request by mroderick**
* Generate Changelog.txt via `git-extras`
* Generate AUTHORS file via `git-extras`
* Create new version via `npm version` (updates package.json and creates a tag)

### CODE REVIEW

**Comment by cjohansen** [comment]
For versions - it seems the bower part is still in there? Also, I suspect we can just use `npm version`?

```sh
       Run this in a package directory to bump the version and write the new data back to the package.json file.

       The  newversion  argument  should be a valid semver string, or a valid second argument to semver.inc (one of "patch", "minor", "major", "prepatch", "premi-
       nor", "premajor", "prerelease"). In the second case, the existing version will be incremented by 1 in the specified field.

       If run in a git repo, it will also create a version commit and tag, and fail if the repo is not clean.
```

As for the changelog: +1

**Comment by mroderick** [comment]
> For versions - it seems the bower part is still in there?

I am not sure how I managed that ... I'll tidy that up ;)

> Also, I suspect we can just use npm version?

I'll look into that :)

**Comment by mroderick** [comment]
I am happy with this PR now, thank you for feedback and ideas!

**Comment by cjohansen** [comment]
Looks very nice :)

**Pull request merged**
