### PR TITLE
sinon.assert with spyCall 1.3.x

### LINKED ISSUE #580: Using sinon.assert with spyCall
Hi, it seems using `sinon.assert` methods with [spyCall](http://sinonjs.org/docs/#spycall) not possible now. 
when trying:
````js
sinon.assert.calledWithMatch(mystub.firstCall, 83, {asd: 1});
````
I'm getting err like this:
````
AssertError: update(83, [object Object]) is not a function
````
Is it correct behavior? 
and if so, any plans to implement spyCalls like spies for assertion?
thanks!

### PR DESCRIPTION
**Pull request by Asgaroth**
closes #580

### CODE REVIEW

**Comment by cjohansen** [comment]
Rebase?

**Comment by Asgaroth** [comment]
@cjohansen not sure what to rebase against, I would like this on a `1.x` branch so I don't have to wait for `2.x`

**Comment by cjohansen** [comment]
master - I left the same comment on #666

**Comment by Asgaroth** [comment]
@cjohansen  #666 is green now.

Isn't master `2.x` ? is there a way we can release a `1.3.4` (or similar) version with this fix?

**Comment by cjohansen** [comment]
2.x is still a branch. We can do a release, but this PR is still failing.

**Comment by Asgaroth** [comment]
@cjohansen #666 its off of master, so I guess we can close this PR, which was off of `1.3.x`

**Comment by cjohansen** [comment]
Ah, ok. I didn't notice that. 1.3 is really old :)

**Pull request closed without merging**
