### PR TITLE
Speed up Travis builds

### PR DESCRIPTION
**Pull request by fearphage**
Changed git clone depth from 50 to 10 to speed up clones (and builds)

### CODE REVIEW

**Comment by cjohansen** [comment]
Smart! Do we even need any depth beyond HEAD to run the CI build?

**Comment by fearphage** [comment]
I've read that depth of 1 causes issues with Travis checking out from branches. 10 is a safe value.

**Comment by cjohansen** [comment]
Ok, cool.

**Comment by fearphage** [comment]
This is ready to merge.

**Pull request merged**
